name: github cli manual trigger
on:
  workflow_dispatch:
    inputs:
      issueNumber:
        description: 'Issue number'


jobs:
  issueList:
    name: List issues
    env:
      GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - run: gh issue list
