name: gh issue list
on:
  workflow_dispatch

jobs:
  issueList:
    name: List issues
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: gh issue list
