name: gh issue view
on:
  workflow_dispatch:
    inputs:
      issueNumber:
        description: 'Issue number'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  issueView:
    name: View an issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: gh issue view ${{ github.event.inputs.issueNumber }}
